function out = model
%
% tezhengpinglv_surface.m
%
% Model exported on Jan 3 2022, 12:53 by COMSOL 5.5.0.292.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('D:\Comsol_Matlab_Test\Original_Model');

model.component.create('comp1', true);

model.component('comp1').geom.create('geom1', 3);

model.component('comp1').mesh.create('mesh1');

model.component('comp1').physics.create('solid', 'SolidMechanics', 'geom1');

model.study.create('std1');
model.study('std1').create('eig', 'Eigenfrequency');
model.study('std1').feature('eig').set('solnum', 'auto');
model.study('std1').feature('eig').set('notsolnum', 'auto');
model.study('std1').feature('eig').set('ngen', '5');
model.study('std1').feature('eig').activate('solid', true);

model.component('comp1').common.create('mpf1', 'ParticipationFactors');

model.component('comp1').geom('geom1').create('imp1', 'Import');
model.component('comp1').geom('geom1').feature('imp1').set('filename', 'D:\BaiduNetdiskDownload\changfengye.stp');
model.component('comp1').geom('geom1').feature('imp1').importData;

model.component('comp1').material.create('mat1', 'Common');
model.component('comp1').material('mat1').label('E glass fiber [solid]');
model.component('comp1').material('mat1').info.create([native2unicode(hex2dec({'54' '08'}), 'unicode')  native2unicode(hex2dec({'62' '10'}), 'unicode')  native2unicode(hex2dec({'72' '69'}), 'unicode') ]);
model.component('comp1').material('mat1').info([native2unicode(hex2dec({'54' '08'}), 'unicode')  native2unicode(hex2dec({'62' '10'}), 'unicode')  native2unicode(hex2dec({'72' '69'}), 'unicode') ]).body('(52-56) SiO2, (12-16) Al2O3, (5-10) B2O3, (16-25) CaO, 5 MgO max, 2 Na2O + K2O max, 1.5 TiO2 max, 0.8 Fe2O3 max (wt%)');
model.component('comp1').material('mat1').propertyGroup('def').set('Syt', 'Syt(T[1/K])[Pa]');
model.component('comp1').material('mat1').propertyGroup('def').set('density', 'rho(T[1/K])[kg/m^3]');
model.component('comp1').material('mat1').propertyGroup('def').func.create('Syt', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('funcname', 'Syt');
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('pieces', {'88.0' '913.0' '5.616846E9-774812.8*T^1-41966.44*T^2+116.198*T^3-0.1241903*T^4+4.546186E-5*T^5'});
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('def').func('Syt').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('def').func.create('rho', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('funcname', 'rho');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('pieces', {'293.0' '303.0' '2580.0'});
model.component('comp1').material('mat1').propertyGroup('def').func('rho').label('Piecewise 1');
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('def').func('rho').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('def').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup.create('Enu', [native2unicode(hex2dec({'67' '68'}), 'unicode')  native2unicode(hex2dec({'6c' '0f'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'54' '8c'}), 'unicode')  native2unicode(hex2dec({'6c' 'ca'}), 'unicode')  native2unicode(hex2dec({'67' '7e'}), 'unicode')  native2unicode(hex2dec({'6b' 'd4'}), 'unicode') ]);
model.component('comp1').material('mat1').propertyGroup('Enu').set('youngsmodulus', 'E(T[1/K])[Pa]');
model.component('comp1').material('mat1').propertyGroup('Enu').set('poissonsratio', 'nu(T[1/K])');
model.component('comp1').material('mat1').propertyGroup('Enu').func.create('E', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('funcname', 'E');
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('pieces', {'293.0' '811.1' '6.712718E10+1.747573E7*T^1'});
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('Enu').func('E').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('Enu').func.create('nu', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('funcname', 'nu');
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('pieces', {'293.0' '783.1' '0.22'});
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').label('Piecewise 1');
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('Enu').func('nu').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('Enu').addInput('temperature');
model.component('comp1').material('mat1').propertyGroup.create('KG', [native2unicode(hex2dec({'4f' '53'}), 'unicode')  native2unicode(hex2dec({'79' 'ef'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'54' '8c'}), 'unicode')  native2unicode(hex2dec({'52' '6a'}), 'unicode')  native2unicode(hex2dec({'52' '07'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode') ]);
model.component('comp1').material('mat1').propertyGroup('KG').set('G', 'mu(T[1/K])[Pa]');
model.component('comp1').material('mat1').propertyGroup('KG').set('K', 'kappa(T[1/K])[Pa]');
model.component('comp1').material('mat1').propertyGroup('KG').func.create('mu', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('funcname', 'mu');
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('pieces', {'293.0' '783.1' '2.751114E10+7162184.0*T^1'});
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').label('Piecewise');
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('KG').func('mu').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('KG').func.create('kappa', 'Piecewise');
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('funcname', 'kappa');
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('arg', 'T');
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('extrap', 'constant');
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('pieces', {'293.0' '783.1' '3.995666E10+1.040222E7*T^1'});
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').label('Piecewise 1');
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('fununit', []);
model.component('comp1').material('mat1').propertyGroup('KG').func('kappa').set('argunit', []);
model.component('comp1').material('mat1').propertyGroup('KG').addInput('temperature');
model.component('comp1').material('mat1').set('family', 'custom');
model.component('comp1').material('mat1').set('lighting', 'cooktorrance');
model.component('comp1').material('mat1').set('specular', 'custom');
model.component('comp1').material('mat1').set('customspecular', [1 1 1]);
model.component('comp1').material('mat1').set('diffuse', 'custom');
model.component('comp1').material('mat1').set('customdiffuse', [1 1 1]);
model.component('comp1').material('mat1').set('ambient', 'custom');
model.component('comp1').material('mat1').set('customambient', [1 1 1]);
model.component('comp1').material('mat1').set('fresnel', 0.99);
model.component('comp1').material('mat1').set('roughness', 0.02);
model.component('comp1').material('mat1').set('shininess', 200);
model.component('comp1').material('mat1').set('alpha', 1);

model.component('comp1').geom('geom1').run;

model.component('comp1').mesh('mesh1').automatic(false);

model.component('comp1').geom('geom1').run('fin');

model.component('comp1').mesh('mesh1').feature('size').set('hauto', 4);
model.component('comp1').mesh('mesh1').run;

model.component('comp1').physics('solid').create('fix1', 'Fixed', 2);
model.component('comp1').physics('solid').feature('fix1').selection.set([18 32 34]);

model.study('std1').feature('eig').set('neigsactive', true);

model.sol.create('sol1');
model.sol('sol1').study('std1');

model.study('std1').feature('eig').set('notlistsolnum', 1);
model.study('std1').feature('eig').set('notsolnum', 'auto');
model.study('std1').feature('eig').set('listsolnum', 1);
model.study('std1').feature('eig').set('solnum', 'auto');

model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').feature('st1').set('study', 'std1');
model.sol('sol1').feature('st1').set('studystep', 'eig');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').feature('v1').set('control', 'eig');
model.sol('sol1').create('e1', 'Eigenvalue');
model.sol('sol1').feature('e1').set('eigvfunscale', 'maximum');
model.sol('sol1').feature('e1').set('eigvfunscaleparam', '1.32E-6');
model.sol('sol1').feature('e1').set('control', 'eig');
model.sol('sol1').feature('e1').feature('aDef').set('cachepattern', true);
model.sol('sol1').attach('std1');

model.result.create('pg1', 'PlotGroup3D');
model.result('pg1').set('data', 'dset1');
model.result('pg1').set('showlegends', false);
model.result('pg1').create('surf1', 'Surface');
model.result('pg1').feature('surf1').set('expr', 'solid.disp');
model.result('pg1').label([native2unicode(hex2dec({'63' '2f'}), 'unicode')  native2unicode(hex2dec({'57' '8b'}), 'unicode') ' (solid)']);
model.result('pg1').feature('surf1').set('colortable', 'AuroraBorealis');
model.result('pg1').feature('surf1').create('def', 'Deform');
model.result('pg1').feature('surf1').feature('def').set('expr', {'u' 'v' 'w'});
model.result('pg1').feature('surf1').feature('def').set('descr', [native2unicode(hex2dec({'4f' '4d'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode')  native2unicode(hex2dec({'57' '3a'}), 'unicode') ]);
model.result.evaluationGroup.create('std1EvgFrq', 'EvaluationGroup');
model.result.evaluationGroup('std1EvgFrq').set('data', 'dset1');
model.result.evaluationGroup('std1EvgFrq').label([native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.evaluationGroup('std1EvgFrq').create('gev1', 'EvalGlobal');
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('expr', 'freq*2*pi', 0);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('unit', 'rad/s', 0);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'89' 'd2'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ], 0);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('expr', 'imag(freq)/abs(freq)', 1);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('unit', '1', 1);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'96' '3b'}), 'unicode')  native2unicode(hex2dec({'5c' '3c'}), 'unicode')  native2unicode(hex2dec({'6b' 'd4'}), 'unicode') ], 1);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('expr', 'abs(freq)/imag(freq)/2', 2);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('unit', '1', 2);
model.result.evaluationGroup('std1EvgFrq').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'54' 'c1'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ], 2);
model.result.evaluationGroup.create('std1mpf1', 'EvaluationGroup');
model.result.evaluationGroup('std1mpf1').set('data', 'dset1');
model.result.evaluationGroup('std1mpf1').label([native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.evaluationGroup('std1mpf1').create('gev1', 'EvalGlobal');
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfLnormX', 0);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 0);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'X ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 0);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfLnormY', 1);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 1);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Y ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 1);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfLnormZ', 2);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 2);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Z ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 2);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfRnormX', 3);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 3);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'X ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 3);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfRnormY', 4);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 4);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Y ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 4);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.pfRnormZ', 5);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', '1', 5);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode')  native2unicode(hex2dec({'5f' '52'}), 'unicode')  native2unicode(hex2dec({'4e' '00'}), 'unicode')  native2unicode(hex2dec({'53' '16'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Z ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 5);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffLX', 6);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg', 6);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'X ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 6);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffLY', 7);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg', 7);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Y ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 7);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffLZ', 8);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg', 8);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Z ' native2unicode(hex2dec({'5e' '73'}), 'unicode')  native2unicode(hex2dec({'79' 'fb'}), 'unicode') ], 8);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffRX', 9);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg*m^2', 9);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'X ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 9);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffRY', 10);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg*m^2', 10);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Y ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 10);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('expr', 'mpf1.mEffRZ', 11);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('unit', 'kg*m^2', 11);
model.result.evaluationGroup('std1mpf1').feature('gev1').setIndex('descr', [native2unicode(hex2dec({'67' '09'}), 'unicode')  native2unicode(hex2dec({'65' '48'}), 'unicode')  native2unicode(hex2dec({'6a' '21'}), 'unicode')  native2unicode(hex2dec({'60' '01'}), 'unicode')  native2unicode(hex2dec({'8d' '28'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'ff' '0c'}), 'unicode') 'Z ' native2unicode(hex2dec({'65' 'cb'}), 'unicode')  native2unicode(hex2dec({'8f' '6c'}), 'unicode') ], 11);

model.sol('sol1').runAll;

model.result('pg1').run;
model.result.evaluationGroup('std1EvgFrq').run;
model.result.evaluationGroup('std1mpf1').run;
model.result.export.create('anim1', 'Animation');
model.result.export('anim1').set('target', 'player');
model.result.export('anim1').set('plotgroup', 'pg1');
model.result.export('anim1').set('sweeptype', 'dde');
model.result.export('anim1').set('maxframes', 11);
model.result.export('anim1').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', 2);
model.result.export.create('anim2', 'Animation');
model.result.export('anim2').set('target', 'player');
model.result.export('anim2').set('plotgroup', 'pg1');
model.result.export('anim2').set('sweeptype', 'dde');
model.result.export('anim2').set('maxframes', 11);
model.result.export('anim2').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', 3);
model.result.export.create('anim3', 'Animation');
model.result.export('anim3').set('target', 'player');
model.result.export('anim3').set('plotgroup', 'pg1');
model.result.export('anim3').set('sweeptype', 'dde');
model.result.export('anim3').set('maxframes', 11);
model.result.export('anim3').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', 4);
model.result.export.create('anim4', 'Animation');
model.result.export('anim4').set('target', 'player');
model.result.export('anim4').set('plotgroup', 'pg1');
model.result.export('anim4').set('sweeptype', 'dde');
model.result.export('anim4').set('maxframes', 11);
model.result.export('anim4').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', 5);
model.result.export.create('anim5', 'Animation');
model.result.export('anim5').set('target', 'player');
model.result.export('anim5').set('plotgroup', 'pg1');
model.result.export('anim5').set('sweeptype', 'dde');
model.result.export('anim5').set('maxframes', 11);
model.result.export('anim5').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', 6);
model.result.export.create('anim6', 'Animation');
model.result.export('anim6').set('target', 'player');
model.result.export('anim6').set('plotgroup', 'pg1');
model.result.export('anim6').set('sweeptype', 'dde');
model.result.export('anim6').set('maxframes', 11);
model.result.export('anim6').run;

model.label('tezhengpinglv_test.mph');

model.sol('sol1').runAll;

model.result('pg1').run;
model.result.export.create('anim7', 'Animation');
model.result.export('anim7').set('target', 'player');
model.result.export('anim7').set('plotgroup', 'pg1');
model.result.export('anim7').set('sweeptype', 'dde');
model.result.export('anim7').set('maxframes', 11);
model.result.export('anim7').run;
model.result.export('anim1').showFrame;
model.result.export('anim2').showFrame;
model.result.export('anim3').showFrame;
model.result.export('anim4').showFrame;
model.result.export('anim5').showFrame;
model.result.export('anim6').showFrame;
model.result.export('anim7').showFrame;
model.result.export('anim1').showFrame;
model.result.export('anim2').showFrame;
model.result.export('anim3').showFrame;
model.result.export('anim5').showFrame;
model.result.export('anim6').showFrame;
model.result.export('anim7').showFrame;
model.result('pg1').run;
model.result('pg1').set('looplevel', [1]);
model.result.export.create('anim8', 'Animation');
model.result.export('anim8').set('target', 'player');
model.result.export('anim8').set('plotgroup', 'pg1');
model.result.export('anim8').set('sweeptype', 'dde');
model.result.export('anim8').set('maxframes', 11);
model.result.export('anim8').run;
model.result('pg1').run;
model.result('pg1').set('looplevel', [5]);
model.result.export.create('anim9', 'Animation');
model.result.export('anim9').set('target', 'player');
model.result.export('anim9').set('plotgroup', 'pg1');
model.result.export('anim9').set('sweeptype', 'dde');
model.result.export('anim9').set('maxframes', 11);
model.result.export('anim9').run;
model.result.export('anim1').showFrame;
model.result.export('anim1').set('target', 'file');
model.result('pg1').run;
model.result.export.create('mesh1', 'Mesh');
model.result.export('mesh1').set('type3D', 'stlascii');
model.result.export('mesh1').set('filename', 'D:\Comsol_Matlab_Test\FanNet\export\Untitled.stl');
model.result.export('mesh1').run;
model.result.export.create('data1', 'Data');
model.result.export('data1').setIndex('looplevelinput', 'manual', 0);
model.result.export('data1').setIndex('looplevel', [5], 0);
model.result.export('data1').set('filename', 'D:\Comsol_Matlab_Test\FanNet\export\Untitled.txt');
model.result.export('data1').run;
model.result.report.create('rpt1', 'Report');
model.result.report('rpt1').set('templatesource', 'complete');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'5b' '9e'}), 'unicode')  native2unicode(hex2dec({'75' '28'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode')  native2unicode(hex2dec({'5e' '8f'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('mpf1', 'ParticipationFactors');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('mpf1').set('noderef', 'mpf1');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'E glass fiber [solid]');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'56' 'fa'}), 'unicode')  native2unicode(hex2dec({'4f' '53'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode')  native2unicode(hex2dec({'5b' '66'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'solid');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'63' '2f'}), 'unicode')  native2unicode(hex2dec({'57' '8b'}), 'unicode') ' (solid)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').create('sec3', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec3').set('heading', [native2unicode(hex2dec({'8b' 'a1'}), 'unicode')  native2unicode(hex2dec({'7b' '97'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').feature('evgr1').set('noderef', 'std1EvgFrq');
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').feature('evgr1').set('noderef', 'std1mpf1');
model.result.report('rpt1').set('format', 'docx');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'5b' '9e'}), 'unicode')  native2unicode(hex2dec({'75' '28'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode')  native2unicode(hex2dec({'5e' '8f'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('mpf1', 'ParticipationFactors');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('mpf1').set('noderef', 'mpf1');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'E glass fiber [solid]');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'56' 'fa'}), 'unicode')  native2unicode(hex2dec({'4f' '53'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode')  native2unicode(hex2dec({'5b' '66'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'solid');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'63' '2f'}), 'unicode')  native2unicode(hex2dec({'57' '8b'}), 'unicode') ' (solid)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').create('sec3', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec3').set('heading', [native2unicode(hex2dec({'8b' 'a1'}), 'unicode')  native2unicode(hex2dec({'7b' '97'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').feature('evgr1').set('noderef', 'std1EvgFrq');
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').feature('evgr1').set('noderef', 'std1mpf1');
model.result.report('rpt1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').create('mesh1', 'Mesh');
model.result.export.create('plot1', 'pg1', 'mesh1', 'Plot');
model.result('pg1').feature('surf1').active(false);
model.result('pg1').feature('surf1').active(true);
model.result.export('plot1').set('filename', 'D:\Comsol_Matlab_Test\FanNet\export\solid.txt');
model.result.export('plot1').run;
model.result.report('rpt1').run;
model.result.report('rpt1').set('filename', 'D:\Comsol_Matlab_Test\FanNet\export\report.docx');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'5b' '9e'}), 'unicode')  native2unicode(hex2dec({'75' '28'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode')  native2unicode(hex2dec({'5e' '8f'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('mpf1', 'ParticipationFactors');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('mpf1').set('noderef', 'mpf1');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'E glass fiber [solid]');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'56' 'fa'}), 'unicode')  native2unicode(hex2dec({'4f' '53'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode')  native2unicode(hex2dec({'5b' '66'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'solid');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'63' '2f'}), 'unicode')  native2unicode(hex2dec({'57' '8b'}), 'unicode') ' (solid)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').create('sec3', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec3').set('heading', [native2unicode(hex2dec({'8b' 'a1'}), 'unicode')  native2unicode(hex2dec({'7b' '97'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').feature('evgr1').set('noderef', 'std1EvgFrq');
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').feature('evgr1').set('noderef', 'std1mpf1');
model.result.report('rpt1').feature.clear;
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', [native2unicode(hex2dec({'51' '68'}), 'unicode')  native2unicode(hex2dec({'5c' '40'}), 'unicode')  native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'65' '70'}), 'unicode') ]);
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').feature('sec1').feature('sec1').feature('param1').set('noderef', 'default');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'c4'}), 'unicode')  native2unicode(hex2dec({'4e' 'f6'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').feature('comp1').set('noderef', 'comp1');
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeauthor', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includedatecreated', true);
model.result.report('rpt1').feature('sec2').feature('comp1').set('includeversion', true);
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'5b' '9a'}), 'unicode')  native2unicode(hex2dec({'4e' '49'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'd8'}), 'unicode')  native2unicode(hex2dec({'91' 'cf'}), 'unicode')  native2unicode(hex2dec({'5b' '9e'}), 'unicode')  native2unicode(hex2dec({'75' '28'}), 'unicode')  native2unicode(hex2dec({'7a' '0b'}), 'unicode')  native2unicode(hex2dec({'5e' '8f'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('mpf1', 'ParticipationFactors');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('mpf1').set('noderef', 'mpf1');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('heading', [native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'8f' 'b9'}), 'unicode')  native2unicode(hex2dec({'75' '4c'}), 'unicode')  native2unicode(hex2dec({'57' '50'}), 'unicode')  native2unicode(hex2dec({'68' '07'}), 'unicode')  native2unicode(hex2dec({'7c' 'fb'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', [native2unicode(hex2dec({'51' 'e0'}), 'unicode')  native2unicode(hex2dec({'4f' '55'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', [native2unicode(hex2dec({'67' '50'}), 'unicode')  native2unicode(hex2dec({'65' '99'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'E glass fiber [solid]');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', [native2unicode(hex2dec({'56' 'fa'}), 'unicode')  native2unicode(hex2dec({'4f' '53'}), 'unicode')  native2unicode(hex2dec({'52' '9b'}), 'unicode')  native2unicode(hex2dec({'5b' '66'}), 'unicode') ]);
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'solid');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', [native2unicode(hex2dec({'7f' '51'}), 'unicode')  native2unicode(hex2dec({'68' '3c'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'6c' '42'}), 'unicode')  native2unicode(hex2dec({'89' 'e3'}), 'unicode')  native2unicode(hex2dec({'56' '68'}), 'unicode')  native2unicode(hex2dec({'91' '4d'}), 'unicode')  native2unicode(hex2dec({'7f' '6e'}), 'unicode') ]);
model.result.report('rpt1').feature('sec3').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').create('sol1', 'Solver');
model.result.report('rpt1').feature('sec3').feature('sec1').feature('sec1').feature('sol1').set('noderef', 'sol1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', [native2unicode(hex2dec({'7e' 'd3'}), 'unicode')  native2unicode(hex2dec({'67' '9c'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', [native2unicode(hex2dec({'65' '70'}), 'unicode')  native2unicode(hex2dec({'63' '6e'}), 'unicode')  native2unicode(hex2dec({'96' 'c6'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', [native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1/' native2unicode(hex2dec({'89' 'e3'}), 'unicode') ' 1']);
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', [native2unicode(hex2dec({'7e' 'd8'}), 'unicode')  native2unicode(hex2dec({'56' 'fe'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', [native2unicode(hex2dec({'63' '2f'}), 'unicode')  native2unicode(hex2dec({'57' '8b'}), 'unicode') ' (solid)']);
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('pg1').set('noderef', 'pg1');
model.result.report('rpt1').feature('sec4').create('sec3', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec3').set('heading', [native2unicode(hex2dec({'8b' 'a1'}), 'unicode')  native2unicode(hex2dec({'7b' '97'}), 'unicode')  native2unicode(hex2dec({'7e' 'c4'}), 'unicode') ]);
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('heading', [native2unicode(hex2dec({'72' '79'}), 'unicode')  native2unicode(hex2dec({'5f' '81'}), 'unicode')  native2unicode(hex2dec({'98' '91'}), 'unicode')  native2unicode(hex2dec({'73' '87'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').feature('evgr1').set('noderef', 'std1EvgFrq');
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').set('heading', [native2unicode(hex2dec({'53' 'c2'}), 'unicode')  native2unicode(hex2dec({'4e' '0e'}), 'unicode')  native2unicode(hex2dec({'56' 'e0'}), 'unicode')  native2unicode(hex2dec({'5b' '50'}), 'unicode') ' (' native2unicode(hex2dec({'78' '14'}), 'unicode')  native2unicode(hex2dec({'7a' '76'}), 'unicode') ' 1)']);
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').create('evgr1', 'EvaluationGroup');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec2').feature('evgr1').set('noderef', 'std1mpf1');
model.result.report('rpt1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('surf1').set('data', 'dset1');
model.result('pg1').run;
model.result('pg1').feature('surf1').set('data', 'parent');
model.result('pg1').run;
model.result.export.create('plot2', 'pg1', 'surf1', 'Plot');
model.result('pg1').feature('mesh1').active(false);
model.result('pg1').feature('mesh1').active(true);
model.result.export('plot2').set('filename', 'D:\Comsol_Matlab_Test\FanNet\export\surface.txt');
model.result.export('plot2').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('mesh1').active(false);
model.result('pg1').feature('mesh1').active(true);
model.result.export('plot2').set('alwaysask', false);
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').run;
model.result.export('anim6').showFrame;
model.result('pg1').run;
model.result('pg1').run;
model.result('pg1').feature('surf1').active(false);
model.result('pg1').feature('surf1').active(true);

out = model;
